# Generated by Django 5.2.4 on 2025-07-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_perfilusuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Link para inscrição em site externo', null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='usar_link_externo',
            field=models.BooleanField(default=False, help_text='Usar link externo em vez do sistema interno'),
        ),
    ]
