# Generated by Django 5.2.4 on 2025-07-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_link_externo_evento_usar_link_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='em_destaque',
            field=models.BooleanField(default=False, help_text='Evento em destaque na página inicial'),
        ),
    ]
