# Generated by Django 5.2.4 on 2025-07-30 22:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_em_destaque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('conteudo', models.TextField()),
                ('resumo', models.TextField(blank=True, help_text='Resumo da notícia para exibição', max_length=500)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20)),
                ('em_destaque', models.BooleanField(default=False, help_text='Notícia em destaque na página inicial')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=500)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_criadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='eventos.categoria')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
