# Generated by Django 5.2.4 on 2025-07-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='estado',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal (formato: 0000-000)', max_length=8),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='concelho',
            field=models.CharField(blank=True, help_text='Concelho/Município', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='distrito',
            field=models.CharField(blank=True, help_text='Distrito', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nif',
            field=models.CharField(blank=True, help_text='Número de Identificação Fiscal (9 dígitos)', max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='endereco',
            field=models.TextField(blank=True, help_text='Rua, número e complemento'),
        ),
    ]
